// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kipnquumtaneeuhxinqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpcG5xdXVtdGFuZWV1aHhpbnFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzk4MzMsImV4cCI6MjA2NDcxNTgzM30.X_C64gUA1qoKX48Vv4l9lgRTuK1UiaH2M_v-UUckwQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);